docs: updated readme
yomorun/react-cursor-chat pull request #10
Opened 2022-03-03 05:55 UTC by Viskeyy

2022-03-03 06:31 UTC, osdodo commented
Already exist hairy-green.png and apricot-yellow.png

2022-03-03 06:35 UTC, fanweixiao requested changes
suggest delete two png files, then we merge. otherwise have to solve the conflicts. @Viskeyy

2022-03-04 02:23 UTC, Viskeyy commented
The conflict has been resolved @fanweixiao

2022-03-07 15:26 UTC, fanweixiao approved these changes

2022-03-07 15:26 UTC, merged