feat: Improve details and optimize README
yomorun/react-cursor-chat pull request #36
Opened 2023-05-19 17:07 UTC by luzhenqian

2023-05-22 02:34 UTC, fanweixiao requested changes

2023-05-22 02:34 UTC, fanweixiao commented on show.gif
please do not delete this, as this is used for README

2023-05-23 16:35 UTC, luzhenqian commented on show.gif
ok, restored

2023-05-24 02:26 UTC, fanweixiao approved these changes

2023-05-24 02:26 UTC, merged